// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWoZubXIbz7gOqd226wIuOyfJ4tcCgdOs',
    appId: '1:367567907905:web:5e40c100eda2fdcdbd6ac0',
    messagingSenderId: '367567907905',
    projectId: 'todoappfirebase-3cb33',
    authDomain: 'todoappfirebase-3cb33.firebaseapp.com',
    storageBucket: 'todoappfirebase-3cb33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkHw8IdakzW2Z-n5j25HjhJEyCYmCBtvo',
    appId: '1:367567907905:android:1c80c9d835053750bd6ac0',
    messagingSenderId: '367567907905',
    projectId: 'todoappfirebase-3cb33',
    storageBucket: 'todoappfirebase-3cb33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaHPQrNZ4eaR8RnVq4lUhNS9UBEbhaEAY',
    appId: '1:367567907905:ios:6cd10aae7f12c04dbd6ac0',
    messagingSenderId: '367567907905',
    projectId: 'todoappfirebase-3cb33',
    storageBucket: 'todoappfirebase-3cb33.appspot.com',
    iosClientId: '367567907905-h2jq4qnf6fihe4560ag5flkvcnugn7em.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaHPQrNZ4eaR8RnVq4lUhNS9UBEbhaEAY',
    appId: '1:367567907905:ios:6cd10aae7f12c04dbd6ac0',
    messagingSenderId: '367567907905',
    projectId: 'todoappfirebase-3cb33',
    storageBucket: 'todoappfirebase-3cb33.appspot.com',
    iosClientId: '367567907905-h2jq4qnf6fihe4560ag5flkvcnugn7em.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppWithFirebase',
  );
}
